server:
  port: 9090   # 配置tomcat端口号
spring:
  application:
    name: air_plane
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/air_ticket?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss    #配置json输出或者输入日期字符串转换Date对象的格式
    time-zone: GMT+8
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss  #配置表单提交数据的日期字符串与Date类型转换
mybatis:
  mapper-locations: classpath:/mappers/*.xml
pagehelper:
  auto-dialect: MYSQL